server:
  ip: localhost
  port: 9090

spring:
  datasource:
    driver-class-name: XXXX
    url: jdbc:XXXX
    username: root
    password: XXXX
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
mybatis:
  mapper-locations: classpath:mapper/*.xml 


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: #########

chatgpt:
  api:
    key: your key
deepseek:
  api:
    key: your key
gemini:
  api:
    key: your key

grok:
  api:
    key: your key


